# Generated by Django 5.2.4 on 2025-07-26 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gname', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(max_length=250)),
                ('ISBN', models.CharField(max_length=13)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='')),
                ('genere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.genere')),
            ],
        ),
    ]
