# Generated by Django 5.2.4 on 2025-07-27 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_user_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='fname',
            new_name='fullName',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lname',
        ),
    ]
