# Generated by Django 5.2.4 on 2025-07-30 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_fname_user_fullname_remove_user_lname'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='quantity',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
